// Classification engine — same rules as the client app (Phase 1+2), source of truth server-side.
const RULES: Array<[RegExp, string]> = [
 [/PAYROLL|DIRECT DEP|DIR DEP|IL STATE UNIV ACH|INTEREST PAID|IRS TREAS|TAX REF|KASASA ATM REFUND|ACCTVERIFY 840|VSA RTN/, 'Income & Refunds'],
 // Credit card payments: issuer names + generic phrasing across banks.
 [/CREDIT CARD|CARD ?PAYMENT|CARD ?PMT|CRD ?PMT|CRDPMT|CC ?PYMT|CC ?PMT|CARDMEMBER|CHASE (CARD|CREDIT|CRD)|\bAMEX\b|AMERICAN EXPRESS|BANKAMERICARD|SYNCHRONY|BARCLAY|CITI ?CARD|CITICARD|COMENITY|BREAD FINANCIAL|DISCOVER.*(E-?PAY|PAYMENT|PMT)|DISCOVER E-PAYMENT|CAPITAL ONE|EPAYMENT|VISA.*(PMT|PAYMENT)|MASTERCARD/, 'Credit Card Payments'],
 [/PAY OFF LOAN|TRANSFER TO LOANS|LOAN ?PMT|LOAN PAYMENT|STUDENT ?LOAN|NELNET|GREAT LAKES|MOHELA|SALLIE MAE|NAVIENT|FEDLOAN|AIDVANTAGE|\bSOFI\b|UPSTART|LENDING ?CLUB|MORTGAGE|MR COOPER|ROCKET ?MORT|FREEDOM MTG|CALIBER HOME/, 'Loan Payments'],
 [/FID BKG|NATL FIN SVC|TRANSFER TO SAVER|ROBINHOOD|VANGUARD|FIDELITY|SCHWAB|ETRADE|E\*TRADE|TD AMERITRADE|COINBASE|BETTERMENT|WEALTHFRONT|ACORNS|\b401K\b|\bROTH\b|IRA CONTRIB|BROKERAGE|CRYPTO\.COM|KRAKEN|BINANCE/, 'Savings & Investments'],
 [/JUD ?MNTGMY COURT|\bCOURT\b|ATTORNEY|LAW OFFICE|\bLEGAL\b/, 'Legal & Court'],
 [/STUDENT APARTMEN|APARTMENT|\bAPTS?\b|RENT ?PMT|RENT PAYMENT|\bRENT\b|\bLEASING\b|PROPERTY ?MGMT|PROPERTY MANAGE|\bREALTY\b|\bHOA\b/, 'Rent & Housing'],
 [/INSURANCE|PROG UNIVERSAL INS|PROGRESSIVE|GEICO|STATE FARM|ALLSTATE|LIBERTY MUT|NATIONWIDE|FARMERS INS|\bUSAA\b|METLIFE|AETNA|CIGNA|BLUE CROSS|\bBCBS\b|ANTHEM|UNITEDHEALTH|HUMANA|ROOT INS|LEMONADE/, 'Insurance'],
 [/XFINITY|COMCAST|VERIZON|T-MOBILE|TMOBILE|AT&T|SPECTRUM|\bELECTRIC\b|\bENERGY\b|PG&E|CON ?ED|DUKE ENERGY|DOMINION|NATIONAL GRID|AMEREN|COMED|NICOR|WATER UTILIT|\bSEWER\b|UTILITY|UTILITIES|CENTURYLINK|FRONTIER|COX COMM|DISH NETWORK|\bINTERNET\b|\bCABLE\b|WASTE ?MGMT|REPUBLIC SERVICES/, 'Utilities & Bills'],
 [/LINCOLN LAND|COLLEGE|TRANSCRIPT|QUIZLET|COMPTIA|\bISU\b|ILLINOIS ?STATE ?UNIVERSI|JONES BARTLETT|CENGAGE|PEARSON|MCGRAW-HILL|WW NORTON|COURSERA|\bUDEMY\b|TUITION|UNIVERSITY|BOOKSTORE|ALAMO II BKST|\bCHEGG\b/, 'Education'],
 [/HRB ONLINE TAX|TAX PREP|TURBOTAX|H&R BLOCK|FRANCHISE TAX|DEPT OF REVENUE/, 'Taxes'],
 [/SPEEDY LUBE|O.REILLY|CAR WASH|\bUBER\b|\bLYFT\b|JIFFY LUBE|VALVOLINE|AUTOZONE|ADVANCE AUTO|NAPA AUTO|\bMIDAS\b|FIRESTONE|GOODYEAR|PEP BOYS|\bDMV\b|\bTOLL\b|IPASS|EZPASS|PARKING|CARMAX|DISCOUNT TIRE|\bTIRE\b/, 'Auto'],
 [/CRUNCH|WORKOUT COMPANY|G\.Y\.M\.|PLANET FITNESS|LA FITNESS|ANYTIME FITNESS|\bYMCA\b|GOLD.S GYM|EQUINOX|ORANGETHEORY|PELOTON|LIFE TIME|CROSSFIT|\bGYM\b|\bFITNESS\b/, 'Gym & Fitness'],
 [/GAME PASS|EB CHICAGO|EB TAKE ME OUT|SQ CAGES|RIOT AN|STUBHUB|GRIFFIN MUS|NAVY PIER|\bXBOX\b|PLAYSTATION|NINTENDO|EPIC GAMES|CINEMARK|\bAMC\b|REGAL CINE|FANDANGO|TICKETMASTER|LIVE NATION|TOPGOLF|DAVE ?& ?BUSTER|SIX FLAGS|\bMUSEUM\b|\bZOO\b|AQUARIUM|BOWLING|\bCONCERT\b|THEATER|THEATRE/, 'Entertainment'],
 [/ATM SERVICE CHARGE|PHONE TRANSFER FEE|TN SERV FEE|FEDEX|\bFEE\b|SERVICE CHARGE|OVERDRAFT|\bNSF\b|FINANCE CHARGE|LATE FEE|MAINTENANCE FEE|FOREIGN TRANSACTION/, 'Fees'],
 [/\bWDL\b|CASH WITHDRAWAL|ATM CASH|ATM WITHDRAW/, 'Cash Withdrawals'],
 [/IMPULSE VAPE|SMOKERS DEN|\bVAPE\b|TOBACCO|SMOKE SHOP|\bCIGAR\b/, 'Vape & Tobacco'],
 [/SUNNY AND REDS|BLUE BELL CLUB|THE VAULT|SIX STRINGS|THE ZONE 24|WESTERN TAP|LIL BEAVER|PUB 2|707 LIQUORS|LUCKY SEVENS|\bBAR\b|TAVERN|\bPUB\b|BREWERY|BREWING|\bLIQUOR\b|WINE ?& ?SPIRITS|NIGHTCLUB|\bLOUNGE\b|SALOON/, 'Bars & Nightlife'],
 [/VITAMIN SHOPPE|\bCVS\b|WALGREENS|RITE AID|SAV-MOR|SPRINGFIELD CLINIC|DENTAL|DENTIST|AMERICA S BEST|PHARMACY|\bCLINIC\b|HOSPITAL|\bMEDICAL\b|URGENT CARE|LABCORP|QUEST DIAG|\bGOODRX\b|OPTOMETR/, 'Health & Pharmacy'],
 [/STEAM ?GAMES|STEAMGAMES|STEAMPOWERED|APPLE\.COM\/BILL|ITUNES|CLAUDE|ANTHROPIC|OPENAI|CHATGPT|LINKEDIN|RESUME\.CO|CCLEANER|AMAZON PRIME|PRIME VIDEO|NETFLIX|SPOTIFY|\bHULU\b|DISNEY ?PLUS|DISNEY\+|\bHBO\b|PARAMOUNT\+|PEACOCK|YOUTUBE ?PREM|YOUTUBE ?TV|AUDIBLE|ADOBE|MICROSOFT 365|OFFICE 365|DROPBOX|NOTION|CANVA|PATREON|SUBSTACK|\bNYT\b|\bWSJ\b|TWITCH|NORDVPN|EXPRESSVPN|1PASSWORD|LASTPASS|GITHUB|GOOGLE ONE|ICLOUD|DASHPASS/, 'Subscriptions & Digital'],
 [/MCDONALD|DAVES HOT CHICKEN|TACO BELL|DAIRY QUEEN|COLDSTONE|DENNYS|DADDIOS|POTRILLOS|MCALISTER|DOMINO|PANDA EXPRESS|FLINGERS|FAT JACKS|FARMERS STATION|PEGGY KINNANES|VINES ON CLARK|SHAKE SHACK|HAWG DINER|SEOUL MAMA|CHIPOTLE|RAISING CANES|JIMMY JOHNS|TRES COMPADRES|ARV BURGERS|HEATERZ|DOORDASH|UBER ?EATS|GRUBHUB|POSTMATES|SEAMLESS|CANTEEN VENDING|\bTST\b|STARBUCKS|SUBWAY|WENDY|BURGER KING|\bKFC\b|POPEYES|\bPIZZA\b|PAPA JOHN|OLIVE GARDEN|APPLEBEE|\bIHOP\b|DUNKIN|CHICK-FIL-A|PANERA|FIVE GUYS|CULVERS|\bSONIC\b|ARBYS|JACK IN THE BOX|WHATABURGER|IN-?N-?OUT|QDOBA|\bMOES\b|JERSEY MIKE|FIREHOUSE|SWEETGREEN|\bCAVA\b|RESTAURANT|\bGRILL\b|\bCAFE\b|COFFEE|TAQUERIA|\bDINER\b|BISTRO|EATERY|STEAKHOUSE|\bBBQ\b|\bSUSHI\b|RAMEN/, 'Dining & Fast Food'],
 [/CASEYS|FAST STOP|AYERCO|ARLINGTON MART|CIRCLE K|PHILLIPS 66|AMITY FOOD MART|\bSHELL\b|\bEXXON\b|\bMOBIL\b|CHEVRON|TEXACO|SUNOCO|VALERO|CITGO|CONOCO|MARATHON|SPEEDWAY|QUIKTRIP|\bWAWA\b|SHEETZ|RACETRAC|\bKWIK\b|\bLOVES\b|PILOT|FLYING J|7-?ELEVEN|\bBP\b|\bFUEL\b|\bGAS\b/, 'Gas & Convenience'],
 [/ALDI|JEWEL OSCO|SCHNUCKS|WAL-?MART|WM SUPERCENTER|WALMART|DOLLAR.GENERAL|DOLLAR TREE|FAMILY DOLLAR|KROGER|\bTARGET\b|COSTCO|SAMS CLUB|WHOLE FOODS|TRADER JOE|PUBLIX|SAFEWAY|MEIJER|FOOD LION|\bHEB\b|H-E-B|WEGMANS|SPROUTS|STOP ?& ?SHOP|HARRIS TEETER|WINCO|\bVONS\b|RALPHS|ALBERTSONS|\bGROCERY\b|SUPERMARKET/, 'Groceries & Household'],
 [/ROSS STORES|TIKTOK SHOP|AMAZON|\bAMZN\b|META STORE|TJMAXX|TJ MAXX|MARSHALLS|ALIEXPRESS|NORMAL GADGETS|THE ITEM SHOP|ADVANCED COMPUTING|HP\.COM|BEST BUY|\bEBAY\b|\bETSY\b|HOME DEPOT|LOWES|\bIKEA\b|WAYFAIR|MACYS|NORDSTROM|KOHLS|OLD NAVY|\bH&M\b|ZARA|\bNIKE\b|ADIDAS|SHEIN|\bTEMU\b|NEWEGG|MICRO CENTER|GAMESTOP|BARNES|CHEWY|PETSMART|PETCO|\bULTA\b|SEPHORA|BATH ?& ?BODY|DICK.S SPORTING|\bREI\b|ACE HARDWARE|MENARDS|HOBBY LOBBY|MICHAELS/, 'Shopping'],
 [/SPORT CLIPS|CSC SERVICEWORK|GREAT CLIPS|SUPERCUTS|\bSALON\b|BARBER|\bNAIL\b|\bSPA\b|MASSAGE|LAUNDR|DRY CLEAN/, 'Personal Care'],
 [/VENMO|CASH ?APP|\bZELLE\b|PAYPAL|PHTFRDDA|PHONE TFR|APPLE CASH/, 'P2P & Transfers']
];
export const ALL_CATS = ['Rent & Housing','Loan Payments','P2P & Transfers','Education','Credit Card Payments','Shopping','Groceries & Household','Legal & Court','Dining & Fast Food','Insurance','Utilities & Bills','Gas & Convenience','Entertainment','Savings & Investments','Subscriptions & Digital','Health & Pharmacy','Gym & Fitness','Auto','Cash Withdrawals','Vape & Tobacco','Bars & Nightlife','Personal Care','Fees','Taxes','Other','Income & Refunds'];

// ---- Dynamic classification via Plaid's own categorization ----
// Plaid tags every transaction with a personal_finance_category (primary + detailed).
// We map that to our buckets so bank-connected data is categorized by Plaid's model,
// not by hardcoded merchant names. Detailed wins (more precise), then primary.
const PFC_DETAILED: Record<string, string> = {
  FOOD_AND_DRINK_GROCERIES: 'Groceries & Household',
  FOOD_AND_DRINK_RESTAURANT: 'Dining & Fast Food',
  FOOD_AND_DRINK_FAST_FOOD: 'Dining & Fast Food',
  FOOD_AND_DRINK_COFFEE: 'Dining & Fast Food',
  FOOD_AND_DRINK_VENDING_MACHINES: 'Dining & Fast Food',
  FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR: 'Bars & Nightlife',
  FOOD_AND_DRINK_NIGHTLIFE: 'Bars & Nightlife',
  TRANSPORTATION_GAS: 'Gas & Convenience',
  TRANSPORTATION_PARKING: 'Auto',
  TRANSPORTATION_PUBLIC_TRANSIT: 'Auto',
  TRANSPORTATION_TAXIS_AND_RIDE_SHARES: 'Auto',
  TRANSPORTATION_TOLLS: 'Auto',
  TRANSPORTATION_BIKES_AND_SCOOTERS: 'Auto',
  RENT_AND_UTILITIES_RENT: 'Rent & Housing',
  RENT_AND_UTILITIES_GAS_AND_ELECTRICITY: 'Utilities & Bills',
  RENT_AND_UTILITIES_WATER: 'Utilities & Bills',
  RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT: 'Utilities & Bills',
  RENT_AND_UTILITIES_TELEPHONE: 'Utilities & Bills',
  RENT_AND_UTILITIES_INTERNET_AND_CABLE: 'Utilities & Bills',
  RENT_AND_UTILITIES_OTHER_UTILITIES: 'Utilities & Bills',
  GENERAL_SERVICES_INSURANCE: 'Insurance',
  GENERAL_SERVICES_EDUCATION: 'Education',
  GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT: 'Taxes',
  PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS: 'Gym & Fitness',
  MEDICAL_PHARMACIES_AND_SUPPLEMENTS: 'Health & Pharmacy',
  ENTERTAINMENT_TV_AND_MOVIES: 'Subscriptions & Digital',
  ENTERTAINMENT_MUSIC_AND_AUDIO: 'Subscriptions & Digital',
  TRANSFER_OUT_SAVINGS: 'Savings & Investments',
  TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS: 'Savings & Investments',
  TRANSFER_OUT_ACCOUNT_TRANSFER: 'P2P & Transfers',
  TRANSFER_OUT_WITHDRAWAL: 'Cash Withdrawals',
  LOAN_PAYMENTS_CREDIT_CARD_PAYMENT: 'Credit Card Payments',
  LOAN_PAYMENTS_MORTGAGE_PAYMENT: 'Loan Payments',
  LOAN_PAYMENTS_CAR_PAYMENT: 'Loan Payments',
  LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT: 'Loan Payments',
  LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT: 'Loan Payments',
  LOAN_PAYMENTS_OTHER_PAYMENT: 'Loan Payments',
  GENERAL_MERCHANDISE_ELECTRONICS: 'Shopping',
  GENERAL_MERCHANDISE_CONVENIENCE_STORES: 'Gas & Convenience'
};
const PFC_PRIMARY: Record<string, string> = {
  INCOME: 'Income & Refunds',
  TRANSFER_IN: 'Income & Refunds',
  TRANSFER_OUT: 'P2P & Transfers',
  LOAN_PAYMENTS: 'Loan Payments',
  BANK_FEES: 'Fees',
  ENTERTAINMENT: 'Entertainment',
  FOOD_AND_DRINK: 'Dining & Fast Food',
  GENERAL_MERCHANDISE: 'Shopping',
  HOME_IMPROVEMENT: 'Shopping',
  MEDICAL: 'Health & Pharmacy',
  PERSONAL_CARE: 'Personal Care',
  GENERAL_SERVICES: 'Other',
  GOVERNMENT_AND_NON_PROFIT: 'Other',
  TRANSPORTATION: 'Auto',
  TRAVEL: 'Entertainment',
  RENT_AND_UTILITIES: 'Utilities & Bills'
};
export function classifyFromPlaid(pfc?: { primary?: string; detailed?: string } | null): string | null {
  if (!pfc) return null;
  if (pfc.detailed && PFC_DETAILED[pfc.detailed]) return PFC_DETAILED[pfc.detailed];
  if (pfc.primary && PFC_PRIMARY[pfc.primary]) return PFC_PRIMARY[pfc.primary];
  return null;
}

export function classify(desc: string, amt: number): string {
  // LOG-2 (intentional simplification): all inflows — payroll, interest, refunds,
  // merchant credits — land in 'Income & Refunds'. Splitting refunds back into
  // their spending category is a Phase-6 enhancement (needs original-purchase
  // matching to avoid double-counting income).
  if (amt > 0) return 'Income & Refunds';
  const u = String(desc).toUpperCase();
  for (const [re, cat] of RULES) if (re.test(u)) return cat;
  return 'Other';
}

const MERCHANTS = ['CASEYS','MCDONALD','DOLLAR GENERAL','VITAMIN SHOPPE','FAST STOP','WAL-MART','WM SUPERCENTER','ALDI','JEWEL OSCO','SCHNUCKS','KROGER','DOLLAR TREE','TACO BELL','DAIRY QUEEN','COLDSTONE','DENNYS','DADDIOS','POTRILLOS','MCALISTER','DOMINO','PANDA EXPRESS','FLINGERS','FAT JACKS','SHAKE SHACK','CHIPOTLE','RAISING CANES','JIMMY JOHNS','DAVES HOT CHICKEN','TIKTOK SHOP','ROSS STORES','AMAZON','META STORE','TJMAXX','HP.COM','APPLE','CLAUDE','ANTHROPIC','OPENAI','QUIZLET','STEAM','RIOT','MICROSOFT','XBOX','STUBHUB','CIRCLE K','PHILLIPS 66','CVS','SAV-MOR','SPORT CLIPS','CRUNCH','IMPULSE VAPE','SMOKERS DEN','ROBINHOOD','CASH APP','VENMO','DISCOVER','CAPITAL ONE','FID BKG','PROG','STUDENT APARTMEN','NETFLIX','SPOTIFY','STARBUCKS','SHELL','TARGET','COSTCO','PLANET FITNESS','GEICO','XFINITY','VERIZON','UBER','LYFT','WILLOW CREEK','BEST BUY','WENDYS','SUBWAY','ACME LOGISTICS'];
const NICE: Record<string, string> = {'MCDONALD':"McDonald's",'CASEYS':"Casey's",'WAL-MART':'Walmart','WM SUPERCENTER':'Walmart','PROG':'Progressive Insurance','STUDENT APARTMEN':'Student Apartments (Rent)','FID BKG':'Fidelity','HP.COM':'HP Store','SAV-MOR':'Sav-Mor Pharmacy','RIOT':'Riot Games','WILLOW CREEK':'Willow Creek Apts (Rent)','ACME LOGISTICS':'Acme Logistics (Payroll)','SHELL':'Shell','XFINITY':'Xfinity','VERIZON':'Verizon','WENDYS':"Wendy's"};

export function cleanDesc(desc: string): string {
  let d = String(desc).replace(/^4274 (VSA PUR|PUR|VSA RECUR|RECUR|VSA RTN|WDL|PMT DB|ATM)\s*/, '').trim();
  return d.replace(/^VSA PUR\s*/, '');
}
export function merchant(desc: string): string {
  const u = String(desc).toUpperCase();
  for (const m of MERCHANTS) {
    if (u.includes(m)) return NICE[m] || m.split(' ').map(w => w.charAt(0) + w.slice(1).toLowerCase()).join(' ');
  }
  let d = cleanDesc(desc).replace(/^(TST|SQ)\s+/, '').replace(/\d{3}-\d{3,}.*/, '').replace(/\s+(IL|CA|WA|NY|NC|OH|VA|MO|TX|FL)$/, '').trim();
  const words = d.split(/\s+/).slice(0, 3);
  if (!words.length || !words[0]) return 'Unknown';
  return words.map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
}
